### ISSUE TITLE
Firefox network.cookie.cookieBehavior level 5 breaks CHAPI get requests

### ISSUE THREAD

**Issue by kdenhartog** [digitalbazaar/credential-handler-polyfill#18]
Looks like Firefox is changing storage configurations in a way that may break CHAPI get() requests.

In Firefox nightly they've set network.cookie.cookieBehavior to level 5 by default now and in Firefox 86.0 with strict protections set, it's now defaulted to level 5. This change in [state partitioning](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/State_Partitioning) affects the ability for CHAPI to request credentials across sites. Right now the thing I've found best to do is in `about:config` adjust `network.cookie.cookieBehavior` to level 4 which turns the dynamic state partitioning back off.

@msporny @dlongley @davidlehn

**Comment by dlongley** [comment]
@kdenhartog,

The credential-handler-polyfill uses the [Storage Access API](https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API) to handle access to cookies and local storage in a third party setting. This is the API that gates getting access to unpartitioned storage in Firefox (and has gated access in Safari for quite some time now). I just successfully tested:

https://chapi-demo-wallet.digitalbazaar.com/
https://chapi-demo-issuer.digitalbazaar.com/
https://chapi-demo-verifier.digitalbazaar.com/

Using Firefox 86 with `network.cookie.cookieBehavior = 5`. I found no issues. Safari has had this kind of storage partitioning for quite a while and so we built in support to address it into the polyfill some years back (2018?). Firefox is just now catching up and implementing double-keyed storage and the Storage Access API that Safari introduced for standardization. (Actually, Firefox has had support for the Storage Access API for a while as well, they are just now making it a necessity to use it to get unpartitioned storage).

Are you reporting that you tried to use CHAPI in Firefox and experienced a failure or are you just commenting on recent announcements/upcoming features in Firefox and how they may happen to affect the polyfill?

If you did experience a failure, can you detail the steps to needed to reproduce? Thanks!

**Comment by kdenhartog** [comment]
Yeah I encountered an error with this yesterday, and after doing a bit of debugging had thought I had narrowed it down to that. It may have to do with our wallet implementation though which relies on IndexDB.

I'll come back Monday with steps to reproduce when we've got all of our implementation publicly available and I can publish links more widely.

**Comment by dlongley** [comment]
I'm going to close this as not actually a bug -- please reopen if it is determined to be a problem.

**Comment by kdenhartog** [comment]
Thanks. I'm running on strict mode now and not having issues, so it may have just been a way in which we had written our wallet at the time.
