### ISSUE TITLE
Add an example of  "wallet-worker.html"

### ISSUE THREAD

**Issue by OR13** [digitalbazaar/credential-handler-polyfill#25]
README provides this example:

```
{
  "icons": [
    {
      "sizes": "48x48 64x64",
      "src": "demo-wallet.png",
      "type": "image/png"
    }
  ],
  "name": "Demo Wallet",
  "short_name": "Demo Wallet",
  "credential_handler": {
    "url": "/wallet-worker.html",
    "enabledTypes": ["VerifiablePresentation"]
  }
}
```

But no html for wallet-worker is available in repo.

**Comment by dlongley** [comment]
+1, we should link to: https://github.com/credential-handler/chapi-demo-wallet/blob/master/wallet-worker.html

**Comment by dlongley** [comment]
We need to (somehow) generally better link up the README here with the documentation and examples from chapi.io.

**Comment by dlongley** [comment]
I've added the link above to the README, but we can still improve with better explanations and examples (again, this needs appropriate coordination with chapi.io).

**Comment by OR13** [comment]
I'm trying to work through a nextjs / typescript wallet example, I will share the react / server side rendering issues here... but so far so good.

**Comment by oznfc** [comment]
Any progress or examples?

**Comment by dlongley** [comment]
The README has been updated to link to [chapi.io](https://chapi.io) which gives a much better introduction to CHAPI along with demos, examples, and a playground. Those examples include an example worker html file. I'm going to close this on that basis.
