### ISSUE TITLE
Remove TODO: Update to something more useful from readme

### ISSUE THREAD

**Issue by OR13** [digitalbazaar/credential-handler-polyfill#27]
```
    const credentialQuery = { web: {} }; // TODO: Update to something more useful
```

Provide at least a simple example

**Comment by OR13** [comment]
Use: 
```
 const credentialQuery =   {
        "web": {
          "VerifiablePresentation": {
            "query": [{
              "type": "QueryByExample",
              "credentialQuery": {
                "reason": "Please present a UniversityDegreeCredential for JaneDoe.",
                "example": {
                  "@context": [
                    "https://w3id.org/credentials/v1",
                    "https://www.w3.org/2018/credentials/examples/v1"
                  ],
                  "type": ["UniversityDegreeCredential"],
                  "credentialSubject": {
                    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21"
                  }
                }
              }
            }]
          },
          "recommendedHandlerOrigins": [
            "https://chapi-demo-wallet.digitalbazaar.com"
          ]
        }
      }
```

**Comment by dlongley** [comment]
@tolson4 -- can you provide a really simple example, something that matches from chapi.io?

**Comment by dlongley** [comment]
I'll tweak the above example and add it real quick. @tolson4, this is another area we'll want to make sure we're aligning / using chapi.io as best as possible here to avoid duplicate maintenance.

**Comment by OR13** [comment]
Why would anyone ever use: 

`recommendedHandlerOrigins`

AFAIK, its undocumented here: https://w3c-ccg.github.io/vp-request-spec/

**Comment by dmitrizagidulin** [comment]
@OR13 so, `recommendedHandlerOrigins` is super useful -- it supports the very common usecase of people /not/ having any wallets installed. So the Origins array provides some suggestions of - hey, if you don't have a wallet, here are some you might want to try.

(And yeah, it should be added to the VPR spec)

**Comment by dlongley** [comment]
This has been updated: https://github.com/credential-handler/credential-handler-polyfill/blob/main/README.md#get

**Comment by dlongley** [comment]
@OR13, @dmitrizagidulin,

"recommendedHandlerOrigins" is not part of VPR, it is part of a `WebCredential` request (so part of the Credential Handler API / CHAPI instead).

**Comment by OR13** [comment]
I am removing it (`recommendedHandlerOrigins`) in my demo, I don't see any documentation or reason to support it

**Comment by OR13** [comment]
imo it should be in the VPR spec... if its in a query... which it is.

Even its its semantics are defined in another spec.

**Comment by dlongley** [comment]
@OR13,

> imo it should be in the VPR spec... if its in a query... which it is.
> 
> Even its its semantics are defined in another spec.

It is not in a VPR query. Your example's indentation was wrong. It's properly fixed in the README.

EDIT: No, your example is right, you just may have been misreading it if you thought it was in the VPR query -- it's not.

**Comment by dlongley** [comment]
@OR13,

The `recommendedHandlerOrigins` CHAPI feature and rationale are now mentioned in the VPR spec here:

https://w3c-ccg.github.io/vp-request-spec/#requesting-and-storing-credentials

**Comment by dlongley** [comment]
Closing as the README has a better example now and it also links to [chapi.io](https://chapi.io) with more information, demos, examples, playground, etc.
