### ISSUE TITLE
Fix URLs in package.json

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/credential-handler-polyfill#45]
URLs in the package.json are pointing at the old `digitalbazaar` location.

https://github.com/credential-handler/credential-handler-polyfill/blob/main/package.json#L8-L19

**Comment by davidlehn** [comment]
This will be fixed by:
https://github.com/credential-handler/credential-handler-polyfill/pull/44
https://github.com/credential-handler/credential-handler-polyfill/pull/44/commits/5862b004e7cbea6333bcbecd7c2e03f41e95d80a

**Comment by davidlehn** [comment]
Should be fixed in latest release.
